---
- name: Discover fleet
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    subnets: "192.168.212.0,192.168.213.0,192.168.214.0"
  tasks:
    - name: Build inventory from subnets
      include_tasks: "./tasks/discover.yaml"

- name: Gather documentation data
  hosts: discovered_fleet
  become: yes
  gather_facts: no
  tasks:
    - name: Create Component-Based View
      include_tasks: "./tasks/{{ item }}.yaml"
      loop:
        - os
        - cpu
        - memory
        - storage
        - network
        - tools
        - docker
        - ip-inventory
        # - backend
        # - frontend
# - name: Create All In One View
#   hosts: localhost
#   gather_facts: no
#   become: no
#   tasks:
#     - name: Run merge playbook
#       include_tasks: ./tasks/merge.yaml
